/** 亲情号称谓类型 */
export enum FAMILY_CONTACT_RELATIONSHIP {
  /** 爸爸 */
  FATHER = 1,
  /** 妈妈 */
  MOTHER = 2,
  /** 爷爷 */
  GRANDFATHER = 3,
  /** 奶奶 */
  GRANDMOTHER = 4,
  /** 外公 */
  MATERNAL_GRANDFATHER = 5,
  /** 外婆 */
  MATERNAL_GRANDMOTHER = 6,
  /** 姐姐 */
  OLDER_SISTER = 7,
  /** 哥哥 */
  OLDER_BROTHER = 8,
  /** 其他 */
  OTHER = 9
}

export type TFamilyContactRelationshipValue = (typeof FAMILY_CONTACT_RELATIONSHIP)[keyof typeof FAMILY_CONTACT_RELATIONSHIP];

export const FAMILY_CONTACT_RELATIONSHIP_I18N: Record<TFamilyContactRelationshipValue, string> = {
  [FAMILY_CONTACT_RELATIONSHIP.FATHER]: "爸爸",
  [FAMILY_CONTACT_RELATIONSHIP.MOTHER]: "妈妈",
  [FAMILY_CONTACT_RELATIONSHIP.GRANDFATHER]: "爷爷",
  [FAMILY_CONTACT_RELATIONSHIP.GRANDMOTHER]: "奶奶",
  [FAMILY_CONTACT_RELATIONSHIP.MATERNAL_GRANDFATHER]: "外公",
  [FAMILY_CONTACT_RELATIONSHIP.MATERNAL_GRANDMOTHER]: "外婆",
  [FAMILY_CONTACT_RELATIONSHIP.OLDER_SISTER]: "姐姐",
  [FAMILY_CONTACT_RELATIONSHIP.OLDER_BROTHER]: "哥哥",
  [FAMILY_CONTACT_RELATIONSHIP.OTHER]: "其他"
};

export const FAMILY_CONTACT_RELATIONSHIP_OPTIONS: Array<{
  label: string;
  value: TFamilyContactRelationshipValue;
}> = [
  {
    label: FAMILY_CONTACT_RELATIONSHIP_I18N[FAMILY_CONTACT_RELATIONSHIP.FATHER],
    value: FAMILY_CONTACT_RELATIONSHIP.FATHER
  },
  {
    label: FAMILY_CONTACT_RELATIONSHIP_I18N[FAMILY_CONTACT_RELATIONSHIP.MOTHER],
    value: FAMILY_CONTACT_RELATIONSHIP.MOTHER
  },
  {
    label: FAMILY_CONTACT_RELATIONSHIP_I18N[FAMILY_CONTACT_RELATIONSHIP.GRANDFATHER],
    value: FAMILY_CONTACT_RELATIONSHIP.GRANDFATHER
  },
  {
    label: FAMILY_CONTACT_RELATIONSHIP_I18N[FAMILY_CONTACT_RELATIONSHIP.GRANDMOTHER],
    value: FAMILY_CONTACT_RELATIONSHIP.GRANDMOTHER
  },
  {
    label: FAMILY_CONTACT_RELATIONSHIP_I18N[FAMILY_CONTACT_RELATIONSHIP.MATERNAL_GRANDFATHER],
    value: FAMILY_CONTACT_RELATIONSHIP.MATERNAL_GRANDFATHER
  },
  {
    label: FAMILY_CONTACT_RELATIONSHIP_I18N[FAMILY_CONTACT_RELATIONSHIP.MATERNAL_GRANDMOTHER],
    value: FAMILY_CONTACT_RELATIONSHIP.MATERNAL_GRANDMOTHER
  },
  {
    label: FAMILY_CONTACT_RELATIONSHIP_I18N[FAMILY_CONTACT_RELATIONSHIP.OLDER_SISTER],
    value: FAMILY_CONTACT_RELATIONSHIP.OLDER_SISTER
  },
  {
    label: FAMILY_CONTACT_RELATIONSHIP_I18N[FAMILY_CONTACT_RELATIONSHIP.OLDER_BROTHER],
    value: FAMILY_CONTACT_RELATIONSHIP.OLDER_BROTHER
  },
  {
    label: FAMILY_CONTACT_RELATIONSHIP_I18N[FAMILY_CONTACT_RELATIONSHIP.OTHER],
    value: FAMILY_CONTACT_RELATIONSHIP.OTHER
  }
];
