/** 设备事件类型 */
export enum DEVICE_EVENT_TYPE {
  /** 命令执行 */
  COMMAND_EXEC = "COMMAND_EXEC",
  /** 人脸识别 */
  FACE_RECOGNIZE = "FACE_RECOGNIZE",
  /** 刷卡识别 */
  CARD_SWIPE = "CARD_SWIPE",
  /** 通话开始 */
  CALL_START = "CALL_START",
  /** 通话结束 */
  CALL_END = "CALL_END",
  /** 查看留言 */
  MESSAGE_VIEW = "MESSAGE_VIEW",
  /** 发送留言 */
  MESSAGE_SEND = "MESSAGE_SEND",
  /** 人脸同步 */
  FACE_SYNC = "FACE_SYNC",
  /** 配置更新 */
  CONFIG_UPDATE = "CONFIG_UPDATE",
  /** 设备启动 */
  DEVICE_BOOT = "DEVICE_BOOT",
  /** 设备上线 */
  DEVICE_ONLINE = "DEVICE_ONLINE",
  /** 设备关机 */
  DEVICE_SHUTDOWN = "DEVICE_SHUTDOWN",
  /** 网络变化 */
  NETWORK_CHANGE = "NETWORK_CHANGE",
  /** APK 升级 */
  APK_UPGRADE = "APK_UPGRADE",
  /** 错误异常 */
  ERROR = "ERROR"
}

export type TDeviceEventTypeValue = (typeof DEVICE_EVENT_TYPE)[keyof typeof DEVICE_EVENT_TYPE];

export const DEVICE_EVENT_TYPE_I18N: Record<TDeviceEventTypeValue, string> = {
  [DEVICE_EVENT_TYPE.COMMAND_EXEC]: "命令执行",
  [DEVICE_EVENT_TYPE.FACE_RECOGNIZE]: "人脸识别",
  [DEVICE_EVENT_TYPE.CARD_SWIPE]: "刷卡识别",
  [DEVICE_EVENT_TYPE.CALL_START]: "通话开始",
  [DEVICE_EVENT_TYPE.CALL_END]: "通话结束",
  [DEVICE_EVENT_TYPE.MESSAGE_VIEW]: "查看留言",
  [DEVICE_EVENT_TYPE.MESSAGE_SEND]: "发送留言",
  [DEVICE_EVENT_TYPE.FACE_SYNC]: "人脸同步",
  [DEVICE_EVENT_TYPE.CONFIG_UPDATE]: "配置更新",
  [DEVICE_EVENT_TYPE.DEVICE_BOOT]: "设备启动",
  [DEVICE_EVENT_TYPE.DEVICE_ONLINE]: "设备上线",
  [DEVICE_EVENT_TYPE.DEVICE_SHUTDOWN]: "设备关机",
  [DEVICE_EVENT_TYPE.NETWORK_CHANGE]: "网络变化",
  [DEVICE_EVENT_TYPE.APK_UPGRADE]: "APK升级",
  [DEVICE_EVENT_TYPE.ERROR]: "错误异常"
};

export const DEVICE_EVENT_TYPE_OPTIONS: Array<{ label: string; value: TDeviceEventTypeValue }> = [
  { label: DEVICE_EVENT_TYPE_I18N[DEVICE_EVENT_TYPE.COMMAND_EXEC], value: DEVICE_EVENT_TYPE.COMMAND_EXEC },
  { label: DEVICE_EVENT_TYPE_I18N[DEVICE_EVENT_TYPE.FACE_RECOGNIZE], value: DEVICE_EVENT_TYPE.FACE_RECOGNIZE },
  { label: DEVICE_EVENT_TYPE_I18N[DEVICE_EVENT_TYPE.CARD_SWIPE], value: DEVICE_EVENT_TYPE.CARD_SWIPE },
  { label: DEVICE_EVENT_TYPE_I18N[DEVICE_EVENT_TYPE.CALL_START], value: DEVICE_EVENT_TYPE.CALL_START },
  { label: DEVICE_EVENT_TYPE_I18N[DEVICE_EVENT_TYPE.CALL_END], value: DEVICE_EVENT_TYPE.CALL_END },
  { label: DEVICE_EVENT_TYPE_I18N[DEVICE_EVENT_TYPE.MESSAGE_VIEW], value: DEVICE_EVENT_TYPE.MESSAGE_VIEW },
  { label: DEVICE_EVENT_TYPE_I18N[DEVICE_EVENT_TYPE.MESSAGE_SEND], value: DEVICE_EVENT_TYPE.MESSAGE_SEND },
  { label: DEVICE_EVENT_TYPE_I18N[DEVICE_EVENT_TYPE.FACE_SYNC], value: DEVICE_EVENT_TYPE.FACE_SYNC },
  { label: DEVICE_EVENT_TYPE_I18N[DEVICE_EVENT_TYPE.CONFIG_UPDATE], value: DEVICE_EVENT_TYPE.CONFIG_UPDATE },
  { label: DEVICE_EVENT_TYPE_I18N[DEVICE_EVENT_TYPE.DEVICE_BOOT], value: DEVICE_EVENT_TYPE.DEVICE_BOOT },
  { label: DEVICE_EVENT_TYPE_I18N[DEVICE_EVENT_TYPE.DEVICE_ONLINE], value: DEVICE_EVENT_TYPE.DEVICE_ONLINE },
  { label: DEVICE_EVENT_TYPE_I18N[DEVICE_EVENT_TYPE.DEVICE_SHUTDOWN], value: DEVICE_EVENT_TYPE.DEVICE_SHUTDOWN },
  { label: DEVICE_EVENT_TYPE_I18N[DEVICE_EVENT_TYPE.NETWORK_CHANGE], value: DEVICE_EVENT_TYPE.NETWORK_CHANGE },
  { label: DEVICE_EVENT_TYPE_I18N[DEVICE_EVENT_TYPE.APK_UPGRADE], value: DEVICE_EVENT_TYPE.APK_UPGRADE },
  { label: DEVICE_EVENT_TYPE_I18N[DEVICE_EVENT_TYPE.ERROR], value: DEVICE_EVENT_TYPE.ERROR }
];
